### ISSUE TITLE
Rename reactNativeEverywhere -> react-native-everywhere

### ISSUE THREAD

**Issue by amilajack** [amoghbanta/react-native-everywhere#11]
This is npm's convention

**Comment by amilajack** [comment]
Github will automatically handle forwarding from old GitHub repo name so users won't see 404's

**Comment by amilajack** [comment]
Why was this closed?

**Comment by amoghbanta** [comment]
hey @amilajack, this issue was resolved, the project has been renamed as per your suggestion.
